# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

def check_plugin()
  unless Vagrant.has_plugin?("vagrant-vbguest")
    raise 'vagrant-vbguest is not installed - please execute "vagrant plugin install vagrant-vbguest" !'
  end
end

check_plugin()

yaml = YAML.load_file('./config.yaml')
nodes = yaml['nodes']
IMAGE = yaml['machine']['image']
MEMORY = yaml['machine']['memory']
CPUS = yaml['machine']['cpus']

Vagrant.configure(2) do |config|

  config.vm.box = IMAGE

  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEMORY
    vb.cpus = CPUS
    vb.gui = true
  end

  # Configure each machine independently
  nodes.each do |node|
    name = node['name']

    node_nets = node['nets']

    config.vm.define name do |box|
      node_nets.each do |net|
        box.vm.network "private_network", virtualbox__intnet: net["netName"], ip: net["ip"], netmask: 24
      end

      box.vm.hostname = name

      box.vm.provider "virtualbox" do |vb|
        vb.name = name
      end

      box.vm.provision "shell" do |s|
        s.privileged = true
        s.path = "provision.sh"
      end

    end
  end
end
